name: Update README
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: muesli/readme-scribe@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: "README.gtpl"
          writeTo: "README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md"
